### ISSUE TITLE
无法实现多页面

### ISSUE THREAD

**Issue by maimiaoliuxin** [breezefeng/vue-cli-multipage#12]
首先我的目录跟你稍微有点不一样。但是关键步骤我是设置了
问题是：只有index.html能正常引入组件，其他html均没有反应（名字问题，不知道为什么）
1】entry设置为多入口，每个页面对应一个js
2】HtmlWebpackPlugin设置不同的html有不同的chunks对应的js文件
3】dev-server.js已经设置各个页面的路径返回对应的html文件

最终效果就是只有index.html 能正常显示，引入js也正确。
但是其他页面html无法引入对应js；并且index.html改为main.html(相应js也改名)，则也不能正常引入对应js

不知道是不是漏了哪个关键步骤？麻烦帮我  解答下，谢谢

**Comment by breezefeng** [comment]
没有任何demo让我怎么给你解答呢
