### ISSUE TITLE
引入axios页面空白

### ISSUE THREAD

**Issue by GR666** [breezefeng/vue-cli-multipage#22]
如题，在下载项目后，npm安装axios，只在src\module\index\index.js文件中添加import axios from 'axios'后，原先正常显示的页面一片空白，浏览器报错Uncaught SyntaxError: import declarations may only appear at top level of a module，如何解决这个问题呢？

**Comment by YungJoker** [comment]
这是来自QQ邮箱的假期自动回复邮件。
 
您好，我最近正在休假中，无法亲自回复您的邮件。我将在假期结束后，尽快给您回复。

**Comment by GR666** [comment]
解决了，使用低版本的axios就可以了
