### ISSUE TITLE
npm run build 报错

### ISSUE THREAD

**Issue by liukang2** [breezefeng/vue-cli-multipage#3]
npm run build 的时候 报error in ./src/module/index/index.js
 module not found:error: a dependency to an entry point is not allowed @ ./src/module/index/index.js 这是咋回事？？？

**Comment by crossingmay** [comment]
把node_modules删了重新装一下试试？应该是安装过程没有完整安装。

**Comment by shadowdq** [comment]
您好，我的也是这个问题，不知道是神魔情况，好几个页面都这样，您能帮忙看看不，万分感谢
