### ISSUE TITLE
好像并不能hot reload。 

### ISSUE THREAD

**Issue by csywweb** [breezefeng/vue-cli-multipage#5]
更改了图片， 并没有hot reload。

**Comment by 3lang3** [comment]
同样问题, hot reload 失效

**Comment by EthanOrange** [comment]
好像多页面下  vue-router 应该屏蔽掉的(不然和多页面是相悖的..)

**Comment by breezefeng** [comment]
使用webstorm有时候hot reload会失效，但是在使用其他编辑器时是不会有这个问题的

**Comment by breezefeng** [comment]
seems Webpack watch doesn't work if the file is not saved directly. Please try turning 'Safe write' option ( Settings | Appearance & Behavior | System Settings | Use "safe write" (save changes to temporary file first)) off

**Comment by breezefeng** [comment]
seems Webpack watch doesn't work if the file is not saved directly. Please try turning 'Safe write' option ( Settings | Appearance & Behavior | System Settings | Use "safe write" (save changes to temporary file first)) off
